name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.PERSONAL_TOKEN }}'
    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          tag_prefix: 'v'
      - uses: Klemensas/action-autotag@stable
        with:
          package_root: '/packages/typebot-js'
          tag_prefix: 'js-lib-v'
  create-latest-tag:
    needs: create-tag
    if: ${{ startsWith(needs.create-tag.outputs.tagname, 'v') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.PERSONAL_TOKEN }}'
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
