on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]

jobs:
  move-linked-issues:
    runs-on: ubuntu-latest
    name: Move linked issues to In Review column
    steps:
      - uses: rharter/github-move-linked-project-cards@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column: Reviewing 👀
