name: Docsearch Scrap

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  scrap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: 'DXYNLHZTGJ'
          algolia_api_key: ${{secrets.DOCSEARCH_API_KEY}}
          file: 'apps/docs/docsearch-scrapper-config.json'
