name: Publish @typebot.io/react package to NPM

on:
  push:
    tags:
      - 'react-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/react
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - run: pnpm publish --no-git-checks --access public
